#!/bin/python3

import sys

bitsize: int = 32

bitsizes: list[int] = { 8, 16, 32, 64, 128 }

if (len(sys.argv) > 1):
    try:
        bitsize = int(sys.argv[1])
    except ValueError as e:
        print(f"[ERR]: {e}") 

if (bitsize not in bitsizes):
    print("Bitsize must be 8/16/32/64 or 128-bit")
    exit(1)

f1 = open("out.c", "w")
f1.write("#include <stdint.h>\n\n")
f1.write(f"uint{bitsize}_t bit[{bitsize}] = {{\n\t")
f1.write("(1 << 0), ")
for i in range(1, bitsize):
    f1.write(("\n\t" if i % 8 == 0 else "") + f"(1 << {i}), ")
f1.write("\n};\n")

f1.close()
