#!/bin/python3

import sys

bitsize: int = 32

bitsizes: list[int] = { 8, 16, 32, 64}

if (len(sys.argv) > 1):
    try:
        bitsize = int(sys.argv[1])
    except ValueError as e:
        print(f"[ERR]: {e}") 

if (bitsize not in bitsizes):
    print("Bitsize must be 8/16/32/64-bit")
    exit(1)
# Open output file
f1 = open("out.c", "w")

f1.write("#include <stdint.h>\n\n")

f1.write(f"uint{bitsize}_t bit[{bitsize}] = {{\n\t")

# Print '1UL' if `bitsize > 32`
ul: str = "UL" if bitsize > 32 else ""

f1.write(f"(1{ul} << 0),")
f1.write("\t\t" if ul == "UL" else "\t")
for i in range(1, bitsize):
    tab: str = "\t\t" if i < 10 and ul == "UL" else "\t"
    f1.write(("\n\t" if i % 8 == 0 else "") + f"(1{ul} << {i}),{tab}")
f1.write("\n};\n")

f1.close()
